Make :udp a symbol
`default: :udp` instead of `default: udp` - which would fail with `NameError (undefined local variable or method 'udp' for main:Object)`

Signed-off-by: Brian Candler <b.candler@pobox.com>